# Generated by Django 5.2.5 on 2025-10-08 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='lat_name',
            new_name='last_name',
        ),
    ]
